export default function SpojOptions() {
    return (
        <>
            <option value="">Select Language</option>
            <option value="7">Ada95 (gnat 8.3)</option>
            <option value="59">Any document (no testing)</option>
            <option value="45">Assembler 32 (gcc 8.3)</option>
            <option value="13">Assembler 32 (nasm 2.14)</option>
            <option value="42">Assembler 64 (nasm 2.14)</option>
            <option value="104">AWK (gawk 4.2.1)</option>
            <option value="105">AWK (mawk 1.3.3)</option>
            <option value="28">Bash (bash 5.0.3)</option>
            <option value="110">BC (bc 1.07.1)</option>
            <option value="12">Brainf**k (bff 1.0.6)</option>
            <option value="81">C (clang 8.0)</option>
            <option value="11">C (gcc 8.3)</option>
            <option value="86">C# (NET 6.0)</option>
            <option value="27">C# (gmcs 5.20.1)</option>
            <option value="41">C++ (g++ 4.3.2)</option>
            <option value="1">C++ (gcc 8.3)</option>
            <option value="82">C++14 (clang 8.0)</option>
            <option value="44">C++14 (gcc 8.3)</option>
            <option value="34">C99 (gcc 8.3)</option>
            <option value="14">Clips (clips 6.30)</option>
            <option value="111">Clojure (clojure 1.10.0)</option>
            <option value="118">Cobol (gnucobol 2.2.0)</option>
            <option value="91">CoffeeScript (coffee 2.4.1)</option>
            <option value="32">Common Lisp (clisp 2.49.92)</option>
            <option value="31">Common Lisp (sbcl 1.4.16)</option>
            <option value="20">D (gdc 8.3)</option>
            <option value="84">D (ldc 1.12.0)</option>
            <option value="102">D (dmd 2.085.0)</option>
            <option value="48">Dart (dart 2.3.0)</option>
            <option value="96">Elixir (elixir 1.8.2)</option>
            <option value="36">Erlang (erl 21.3.8)</option>
            <option value="124">F# (mono 4.1)</option>
            <option value="92">Fantom (fantom 1.0.72)</option>
            <option value="107">Forth (gforth 0.7.3)</option>
            <option value="5">Fortran (gfortran 8.3)</option>
            <option value="114">Go (go 1.12.1)</option>
            <option value="121">Groovy (groovy 2.5.6)</option>
            <option value="21">Haskell (ghc 8.4.4)</option>
            <option value="16">Icon (iconc 9.5.1)</option>
            <option value="9">Intercal (ick 0.3)</option>
            <option value="10">Java (HotSpot 12)</option>
            <option value="35">JavaScript (rhino 1.7.9)</option>
            <option value="112">JavaScript (SMonkey 60.2.3)</option>
            <option value="80">Julia (julia 1.5.3)</option>
            <option value="47">Kotlin (kotlin 1.3.21)</option>
            <option value="26">Lua (luac 5.3.3)</option>
            <option value="30">Nemerle (ncc 1.2.547)</option>
            <option value="25">Nice (nicec 0.9.13)</option>
            <option value="122">Nim (nim 0.19.4)</option>
            <option value="56">Node.js (node 11.12.0)</option>
            <option value="43">Objective-C (gcc 8.3)</option>
            <option value="83">Objective-C (clang 8.0)</option>
            <option value="8">Ocaml (ocamlopt 4.05.0)</option>
            <option value="127">Octave (octave 4.4.1)</option>
            <option value="2">Pascal (gpc 20070904)</option>
            <option value="22">Pascal (fpc 3.0.4)</option>
            <option value="60">PDF (ghostscript 8.62)</option>
            <option value="3">Perl (perl 5.28.1)</option>
            <option value="54">Perl (perl 2018.12)</option>
            <option value="29">PHP (php 7.3.5)</option>
            <option value="94">Pico Lisp (pico 18.12.27)</option>
            <option value="19">Pike (pike 8.0)</option>
            <option value="61">PostScript (ghostscript 8.62)</option>
            <option value="15">Prolog (swi 7.6.4)</option>
            <option value="108">Prolog (gprolog 1.4.5)</option>
            <option value="109">Python 3 (PyPy 3.6.1)</option>
            <option value="117">R (R 3.5.2)</option>
            <option value="95">Racket (racket 7.0)</option>
            <option value="17">Ruby (ruby 2.5.5)</option>
            <option value="93">Rust (rust 1.56)</option>
            <option value="39">Scala (scala 2.12.8)</option>
            <option value="33">Scheme (guile 2.2.4)</option>
            <option value="97">Scheme (chicken 4.13)</option>
            <option value="18">Scheme (stalin 0.11)</option>
            <option value="46">Sed (sed 4.7)</option>
            <option value="23">Smalltalk (gst 3.2.5)</option>
            <option value="40">SQLite (sqlite 3.27.2)</option>
            <option value="85">Swift (swift 4.2.2)</option>
            <option value="38">TCL (tcl 8.6)</option>
            <option value="62">Text (plain text)</option>
            <option value="115">Unlambda (unlambda 0.1.4.2)</option>
            <option value="50">VB.net (mono 4.7)</option>
            <option value="6">Whitespace (wspace 0.3)</option>
        </>
    );
}
